name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Add upstream remote
        run: git remote add upstream https://github.com/redis/jedis.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream
        run: git merge upstream/main
      - name: Push to origin
        run: git push origin main